CC=g++
CFLAGS=-Wall -std=c++98

build: p1 p3 p4

p1:
	$(CC) $(CFLAGS) -o p1 points.cpp

p3:
	$(CC) $(CFLAGS) -o p3 stropitori.cpp

p4: 
	$(CC) $(CFLAGS) -o p4 warriors.cpp

run-p1: p1
	./p1

run-p3: p3
	./p3

run-p4: p4
	./p4

clean:
	rm -rf p1 p3 p4
